### ISSUE TITLE
No Database ID provided when using the observers

### ISSUE THREAD

**Issue by ibaraki-douji** [blackfan23/ngx-appwrite#2]
Hi, after using two databases on my projects i wanted to observe change in one of them but when using the `documentList$` with the `alternateDatabaseId` it still does the error.

After looking at the code i found out you don't add the `alternateDatabaseId` here : https://github.com/blackfan23/ngx-appwrite/blob/a9016e84e10c64d184d8cee18c2991e1d3deb9f0/libs/ngx-appwrite/src/lib/databases.ts#L278
wich cause the list to fail

**Comment by ibaraki-douji** [comment]
And also no i don't use default database

**Comment by blackfan23** [comment]
Thank you for raising the issue and solving it, I'll add a fix as soon as I get a chance.

**Comment by blackfan23** [comment]
Added version 1.5 and fixed the issue hopefully.

**Comment by ibaraki-douji** [comment]
yup fixed and it works fine
