### ISSUE TITLE
[Feature] Add all the execution settings

### ISSUE THREAD

**Issue by ibaraki-douji** [blackfan23/ngx-appwrite#3]
Hey,
If possible could you add the missing elements from the function execution ?? (path, method, headers)

https://github.com/blackfan23/ngx-appwrite/blob/0202fb6395513ceec59d6af7cc36e607873078f3/libs/ngx-appwrite/src/lib/functions.ts#L44

This is a little bit sad to not includes them since it can work with that.

**Comment by blackfan23** [comment]
I'll have a look at it tonight, thanks for your feedback

**Comment by ibaraki-douji** [comment]
thx ;)
