### ISSUE TITLE
[Bug] Cannot create on custom DB / with custom ID

### ISSUE THREAD

**Issue by ibaraki-douji** [blackfan23/ngx-appwrite#4]
You don't pass the same params from the adapter to the DB service witch cause it to fail.
I didn't really tested the custom ID but on what i see it will not work

https://github.com/blackfan23/ngx-appwrite/blob/0202fb6395513ceec59d6af7cc36e607873078f3/libs/ngx-appwrite/src/lib/appwrite.adapter.ts#L35

https://github.com/blackfan23/ngx-appwrite/blob/0202fb6395513ceec59d6af7cc36e607873078f3/libs/ngx-appwrite/src/lib/databases.ts#L50

**Comment by ibaraki-douji** [comment]
for a rapid fix you can add `awDocument.$id` just before the `alternativeDatabaseId` param or add a param to the `create` function and pass it to the `createDocument`

**Comment by blackfan23** [comment]
Thank you for opening this issue. I'll fix it with the next release

**Comment by ibaraki-douji** [comment]
yup it works fine now
